# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
.chromatid_value <- function(xodat, map, founder, eff) {
    .Call('simbreed_chromatid_value', PACKAGE = 'simbreed', xodat, map, founder, eff)
}

#' @export
.gamete_value <- function(xodat, map, founder, eff) {
    .Call('simbreed_gamete_value', PACKAGE = 'simbreed', xodat, map, founder, eff)
}

#' @export
.gamete_value2 <- function(parent, params, map, founder, eff) {
    .Call('simbreed_gamete_value2', PACKAGE = 'simbreed', parent, params, map, founder, eff)
}

#' @export
.bcgv <- function(parent, n_gam, n_rep, se_thresh, params, map, founder, eff) {
    .Call('simbreed_bcgv', PACKAGE = 'simbreed', parent, n_gam, n_rep, se_thresh, params, map, founder, eff)
}

#' @export
.xo2geno_chromatid <- function(xodat, map, founder) {
    .Call('simbreed_xo2geno_chromatid', PACKAGE = 'simbreed', xodat, map, founder)
}

#' @export
.xo2geno_chromosome <- function(xodat, map, founder, homozygous) {
    .Call('simbreed_xo2geno_chromosome', PACKAGE = 'simbreed', xodat, map, founder, homozygous)
}

#' @export
.xo2geno_individual <- function(xodat, map, founder) {
    .Call('simbreed_xo2geno_individual', PACKAGE = 'simbreed', xodat, map, founder)
}

#' @export
.xo2geno_gamete <- function(xodat, map, founder) {
    .Call('simbreed_xo2geno_gamete', PACKAGE = 'simbreed', xodat, map, founder)
}

#' @export
.xo2geno_population <- function(xodat, map, founder) {
    .Call('simbreed_xo2geno_population', PACKAGE = 'simbreed', xodat, map, founder)
}

#' @export
xo2geno <- function(xodat, map, founder) {
    .Call('simbreed_xo2geno', PACKAGE = 'simbreed', xodat, map, founder)
}

#' @export
.gamete <- function(parent, params) {
    .Call('simbreed_gamete', PACKAGE = 'simbreed', parent, params)
}

#' @export
.cross <- function(mother, father, params) {
    .Call('simbreed_cross', PACKAGE = 'simbreed', mother, father, params)
}

.realized_IBD_chromatids <- function(chromatid1, chromatid2) {
    .Call('simbreed_realized_IBD_chromatids', PACKAGE = 'simbreed', chromatid1, chromatid2)
}

.realized_IBD <- function(ind1, ind2) {
    .Call('simbreed_realized_IBD', PACKAGE = 'simbreed', ind1, ind2)
}

#' @export
.sim_crossovers <- function(L, m, p, obligate_chiasma, Lstar) {
    .Call('simbreed_sim_crossovers', PACKAGE = 'simbreed', L, m, p, obligate_chiasma, Lstar)
}

#' @export
sim_meiosis_xo <- function(parent, Xlocations) {
    .Call('simbreed_sim_meiosis_xo', PACKAGE = 'simbreed', parent, Xlocations)
}

#' @export
sim_meiosis_xo_test <- function(parent, Xlocations) {
    .Call('simbreed_sim_meiosis_xo_test', PACKAGE = 'simbreed', parent, Xlocations)
}

#' @export
sim_meiosis_reliable <- function(parent, L, m, p, obligate_chiasma, Lstar) {
    .Call('simbreed_sim_meiosis_reliable', PACKAGE = 'simbreed', parent, L, m, p, obligate_chiasma, Lstar)
}

#' @export
.sim_meiosis <- function(parent, L, m, p, obligate_chiasma, Lstar) {
    .Call('simbreed_sim_meiosis', PACKAGE = 'simbreed', parent, L, m, p, obligate_chiasma, Lstar)
}

